### ISSUE TITLE
Question, how to handle fragment listeners?

### ISSUE THREAD

**Issue by bentrengrove** [PandoraMedia/BottomNavigator#10]
Does the Pandora app ever have the situation where a fragment has a listener and that listener is the fragment that opened it? How is this handled if so? Put another way, how do you pass information back up the back state?

We currently achieve this using child fragments but it creates a mess of back state and attach the listener in onAttach by looking up the parent fragment. Evaluating options for fixing it currently and wondering if you have run in to the same situation.

**Comment by guelo** [comment]
I think a shared ViewModel can be a good pattern for communicating between fragments. This techniques is described here https://developer.android.com/topic/libraries/architecture/viewmodel.html#sharing

**Comment by bentrengrove** [comment]
I'm not sure that covers all cases. We have fragments that are opened from multiple different spots in the app. The PR that is open currently basically is a way to handle my question. No problem though if it isn't supported
