### ISSUE TITLE
clear backstack on tab click

### ISSUE THREAD

**Issue by orbitcoder** [PandoraMedia/BottomNavigator#11]
**Is there any way to clear all back stack and move to first fragment  when clicked on tab?**

**any way to open default fragment as last fragment of activity when back pressed? "**

**Comment by guelo** [comment]
> Is there any way to clear all back stack and move to first fragment when clicked on tab?
If I understand your question correctly BottomNavigator should handle this automatically.

> any way to open default fragment as last fragment of activity when back pressed? "
I'm not sure I understand the question. When BottomNavigator runs to pop it returns false so you could do something there in Activity's onBackPressed:

```kotlin
    override fun onBackPressed() {
        if (!navigator.pop()) {
          // Navigator has no more fragments to remove, do something special here
        }
    }
```

Does that answer the question?
