### ISSUE TITLE
Clear the Backstack when return to tabs

### ISSUE THREAD

**Issue by dinhthaidaica** [PandoraMedia/BottomNavigator#23]
Let's say I have 3 tabs: **Tab1**, **Tab2**, and **Tab3**. 
Each tab has its own back stack. 

Now I'm in **Tab1**, then add some other fragments into tab1's stack.
Then I switch to **Tab2** or **Tab3**.

**_Question_**: When I click on **Tab1**, is there any way to clear its back stack to get back to the root fragment?

**Comment by guelo** [comment]
You could subscribe to the infoStream() and look for the TabSwitched events and then call `reset(R.id.tab1)`
